tailwindlabs/tailwindcss-typography

src/styles.js
Fixes #6
```js
round(20) // -> '20'
round(1 / 3) // -> '0.3333333'
round(2 / 3) // -> '0.6666667'
round(2 / 10) // -> '0.2'
```
Also makes use of the `round` helper in the `rem` helper
=> Fix rounding when number is whole & ends with 0

demo/components/MarkdownSample.mdx
Pardon the nitpicking …
I loved reading through this text, though! :-)
btw: this is a tilde `~`
=> Fix some minor typos in the demo content

src/styles.js
This PR swaps any usage of `.lead` in our default CSS for `[class~="lead"]` to avoid a unexpected output when generating the responsive variants of the `prose` class.
Currently, Tailwind always adds the responsive prefix (`sm:` for example) to the _last_ class in a selector, and only that class. That means that before this PR, we were getting output like this:
```css
@media (min-width: 640px) {
.sm\:prose {
color: #4a5568;
max-width: 65ch;
}
.prose .sm\:lead {
color: #4a5568;
font-size: 1.25em;
/* ... */
}
.sm\:prose a {
color: #1a202c;
text-decoration: underline;
}
/* ... */
}
```
Notice how the second selector is incorrect, it should be `.sm\:prose .lead` for the plugin to behave the way people expect.
Tailwind's behavior is justifiable and makes more sense in a lot of circumstances, …
=> Use attribute selector instead of class to avoid prefixing the wrong class

README.md
I thought it would be a good idea to do this since some people (#14 ) couldn't figure out how to use the `theme()` helper function, and stuff like this should be documented anyways.
=> Added a section regarding how to use the `theme()` helper function to the docs

package.json, src/index.js, src/index.test.js, src/styles.js, src/utils.js, yarn.lock
This PR adds new color modifiers by default like `prose-indigo`, `prose-blue`, `prose-pink`, etc. that update link colors to match the modifier color. Useful for adding a little bit of branding to your content sections.
It uses the `600` shade of each color in your `theme.colors` configuration by default, excluding `gray`. If a color doesn't have a `600` shade it is skipped.
This is implemented simply as a default config, and not as any special logic inside the plugin. You can control which ones are enabled just like the size modifiers:
```js
// tailwind.config.js
module.exports = {
theme: {
// ...
},
plugins: [
require('@tailwindcss/typography')({
modifiers: ['sm', 'lg', 'blue', 'pink'],
}),
// ...
],
}
```
=> Add color modifiers

src/index.test.js, src/styles.js
There is a bug in how the `prose-{color}` helpers are generated. Since this is `reduce` and not `map`, returning `{}` was effectively erasing any existing valid colors (usually the default colors) if someone created a custom color (by extending `colors`) that had no `600` value set.
Proof of concept here:
https://play.tailwindcss.com/IVTa5zHqPJ?file=config
Thanks to @RobinMalfait for helping me figure out the best way to move this issue forward.
=> Fix bug related to prose color helpers not working as expected

src/index.test.js, src/styles.js
I have no push access to #85, but the tests were missing. Fixed the tests, and included the original commit so that @neupauer is still marked as a contributor!
---
Closes #75 
Closes #85
Resolves #71
=> Use implicit `list-item` counter

package.json, src/index.test.js, src/styles.js, yarn.lock
This PR will make sure that the linked PR is updated correctly with the new syntax.
Closes: #41
Closes: #77
=> use `content: none;` instead of `content: '';`

src/index.test.js, src/styles.js
This is an extension on top of the pr #72
This pr adds `""` around the `I s` for example.
This pr is also a rebase on top of `masters`.
Added @neupauer as a co-author to still mark them as a contributor.
=> keep `type` on `ol` elements in mind

src/index.test.js, src/styles.js
Case-sensitive modifier `s` should be outside the attribute value. This PR fix that. Eg. `ol[type="A s"]` -> `ol[type="A" s] `
Visual preview of the result: 
Currently only Firefox displays all types correctly until the Chrome (Edge, Opera) bug is resolved. 
See [MDN - Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#browser_compatibility)
=> Fix ordered list style type `s` modifier position

src/index.test.js, src/styles.js
Closes #170.
This PR adds some basic styles for `strong` elements nested in headings. Kind of an uncommon thing to do, but the previous behavior was actually making strong elements _lighter_ than the heading which feels bad. This makes strong text one level bolder than the surrounding heading text, which is at least better.
=> Add strong styles for headings

README.md
I was having trouble explaining the `prose` class to my students, so I decided to look through the documentation to see if I could change the name.
I came across [this issue](https://github.com/tailwindlabs/tailwindcss-typography/issues/16), where @adamwathan last commented 
> It should work in the latest release, just haven't written release notes yet sorry.
I tried setting the class name to typography on a local nuxt build, and it worked perfectly, so I went ahead and created a PR to add this to the README documentation.
=> Added docs for changing the default class name

src/index.js, src/index.test.js
This PR changes the output of this plugin to use the [:where pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:where) to reduce the specificity of the selectors, making it possible to easily override typography styles with utilities.
Here's an example of how the output has changed:
```diff
- .prose a code {
+ .prose :where(a code) {
color: #111827;
}
```
Prior to this PR, using a utility like this to override a typography style like this wouldn't work unless you enabled the `important` option in your `tailwind.config.js` file:
```html
<div class="prose">
<p>
The <a href="#"><code class="text-green-500">:where pseudo-class</code></a> is awesome.
</p>
</div>
```
After merging this PR, the code above will just work 🥳 This solves one of the most common pain points of working …
=> Use :where to reduce specificity

.github/workflows/release-insiders.yml
Publish a new `insiders` build everything a new commit gets pushed onto
the `master` branch.
=> Add release-insiders workflow

CHANGELOG.md, src/index.js, src/index.test.js
Partial fix for https://github.com/tailwindlabs/tailwindcss/issues/6336
You can customize the config to control the default CSS that's generated and multiple values are intended to support fallback values for properties.
For example:
```js
css: {
textAlign: ['-webkit-match-parent', 'match-parent'],
}
```
should result in:
```css
.prose {
text-align: -webkit-match-parent;
text-align: match-parent;
}
```
However passing in an array resulted in invalid CSS. This fixes that. There is a second problem in tailwind itself which causes the above to only take the last value in the array so instead you end up with this:
```css
.prose {
text-align: match-parent;
}
```
That problem will need to be solved separately but we are at least now generating valid css.
=> Don't generate invalid CSS when given an array of property values

CHANGELOG.md, jest/customMatchers.js, src/index.js, src/index.test.js
This PR will fix an issue where nested configuration in the `tailwind.config.js` didn't get the correct selector.
E.g.:
```js
theme: {
extend: {
typography: {
DEFAULT: {
css: {
a: {
color: '#888',
'&:hover': {
color: '#ff0000',
},
},
},
},
},
},
},
```
This generated the incorrect css:
```css
.prose a {
color: #888;
text-decoration: underline;
font-weight: 500;
}
:where(.prose a:hover):not(:where([class~="not-prose"] *)) {
color: #FF0000;
}
```
This means that the non-hover version still has higher specificity. The output we want is this:
```css
.prose :where(a):not(:where([class~='not-prose'] *)) {
color: #888;
text-decoration: underline;
font-weight: 500;
}
.prose :where(a):not(:where([class~='not-prose'] *)):hover {
color: #ff0000;
}
```
Fixes: #231
=> Ensure nested selectors using `&:hover` work

src/styles.js
Fixes #250
---
This could have been caught with ESLint. We could configure with an `.eslintrc.json` like:
```json
{
"parserOptions": {
"ecmaVersion": "latest",
"sourceType": "module",
"ecmaFeatures": {
"jsx": true
}
},
"env": {
"node": true,
"jest": true
},
"extends": "eslint:recommended"
}
```
And it would have complained like this:
```
tailwindcss-typography/src/styles.js
108:9  error  Duplicate key 'ol'  no-dupe-keys
114:9  error  Duplicate key 'ul'  no-dupe-keys
290:9  error  Duplicate key 'ol'  no-dupe-keys
296:9  error  Duplicate key 'ul'  no-dupe-keys
472:9  error  Duplicate key 'ol'  no-dupe-keys
478:9  error  Duplicate key 'ul'  no-dupe-keys
654:9  error  Duplicate key 'ol'  no-dupe-keys
660:9  error  Duplicate key 'ul'  no-dupe-keys
836:9  error  Duplicate key 'ol'  no-dupe-keys …
```
=> Fix duplicate keys issue with `ol` and `ul`

src/index.js, src/index.test.js
I try to fix #258, not sure it is the correct way right now.
=> Fix prose elements `legacy` mode. Fixes #258

CHANGELOG.md, src/index.js, src/index.test.js
Right now the `lead` class cannot override element styles because it's quite a bit higher in the output. This causes `lead` to act different if it's a div verus a p tag, a tag, etc… The margins from the `p` tag override any `p.lead` element when it should be the other way around.
Fixes #256
=> Allow `lead` class to override element styles

src/styles.js
Fixes #257
This PR fixes `figure` spacing by ensuring that the `figure > *` selector (which removes margins) appears _after_ the `img` selector (which adds margins)
=> Fix `figure` spacing

src/index.js, src/index.test.js
Fixes #266
This PR fixes selector generation when the selector starts with a child combinator (`>`), e.g. `> ul > li p`
**Before**
```css
.prose > :where(ul > li p)
```
**After**
```css
.prose :where(.prose > ul > li p)
```
=> Fix child combinator `:where` selectors

CHANGELOG.md, src/index.js, src/index.test.js
I find the argumentation in issue #262 reasonable.
It would be great though to be able to add custom styles for headings h5 and h6 via `prose-h5:...` and `prose-h6:...`.
This pull request enables this functionality, without specifying styles for these headings.
=> Add h5 and h6 options to plugin

src/styles.js
Resolves #275
This PR updates the `strong` and `code` color styles in the typography plugin to inherit parent colors. Right now this isn't the case, and if you add a custom color to say a heading or blockquote, and then include either a `<strong>` or `<code>` tag within that element, they will get their default colors...not the custom color of the parent.
For example, like this: 
With this change the `<strong>` and `<code>` elements will now automatically inherit the custom color from the parent:
This feels like a more sensible way of handling these child element colors.
=> Update `strong` and `code` colors to inherit from parent

package-lock.json, package.json, src/index.js, src/index.test.js, src/utils.js
Fixes #280
There are some bugs in Tailwind's own selector rewriting for variants but also some bugs in the typography plugin selector rewriting. Use `postcss-selector-parser` to more properly handle selector rewriting of trailing pseudo elements.
This fixes the selector rewriting to check _all_ simple selector sequences in each of the keys in `theme.typography.*.css` and extracts `::before`, `::after`, `::marker`, and any other pseudo element only when they're the same across each of the selectors — including order. The reason for this is that it's possible in the future stacked pseudo elements could become a thing (there's a note in the CSS spec somewhere — but I forget where) meaning `::marker::before` could mean something different from `::before::marker` (even though both don't make …
=> Move common, trailing pseudo elements when generating selectors

src/index.js, src/index.test.js
Fixes #287
This PR fixes generated selectors when using a modifier (e.g. `prose-sm`):
```diff
- .prose-sm :where(.prose > :first-child):not(:where([class~="not-prose"] *)) {
+ .prose-sm :where(.prose-sm > :first-child):not(:where([class~="not-prose"] *)) {
margin-top: 0;
}
```
=> Fix selector when using a non-default class (e.g. `prose-sm`)

src/index.test.js, src/styles.js
Fixes #293 
Fixed by adding an empty `p` object to the `DEFAULT` styles. We do the same thing for `img`: https://github.com/tailwindlabs/tailwindcss-typography/blob/fda8ce5f8013b02768aa066a8bc34197d6947cad/src/styles.js#L1351-L1352
=> Ensure `p` styles are inserted before `.lead` styles

CHANGELOG.md, src/styles.js
Fixes #304
This PR fixes a spacing issue when putting a code block within a `<figure>`, where the margin on the `<pre>` wasn't being removed due to an ordering issue. This is a similar issue to #267.
By moving the figure styles to the end, the `figure > *` margin reset now takes priority over the specific element margin styles.
Before:
<kbd><img width="1092" alt="image" src="https://github.com/tailwindlabs/tailwindcss-typography/assets/882133/d517f650-71aa-401c-9aff-49279411bd08"></kbd>
After:
<kbd><img width="1088" alt="image" src="https://github.com/tailwindlabs/tailwindcss-typography/assets/882133/765eefd3-6c32-41fd-b3f4-a0db8f9e48f4"></kbd>
=> Fix space between `<figcaption>` and `<pre>`

CHANGELOG.md, src/index.js, src/index.test.js
=> Remove typography styles from `not-prose` elements in addition to their children

CHANGELOG.md, src/styles.js
Fixes #228
This PR fixes an issue where `prose-invert` wasn't working when used with a `prose-{color}` modifier while in light mode. For example:
```html
<div class="prose prose-invert prose-slate bg-slate-900 p-12">
Lorem ipsum dolor sit amet...
</div>
```
Prior to this fix you'd get this:
<kbd><img width="653" alt="image" src="https://github.com/tailwindlabs/tailwindcss-typography/assets/882133/4df3869f-b5b9-4732-97fe-3f0058bb14c5"></kbd>
With this change, you get this:
<kbd><img width="652" alt="image" src="https://github.com/tailwindlabs/tailwindcss-typography/assets/882133/5a163182-e2b3-4e81-83ed-5be107c00fb7"></kbd>
The solution here is what @adamwathan [suggested](https://github.com/tailwindlabs/tailwindcss-typography/issues/228#issuecomment-1049023163) in the linked issue, where …
=> Fix `prose-invert` when used with colors in light mode

CHANGELOG.md, demo/components/MarkdownSample.mdx, src/styles.js
Resolves #146
This PR adds styles for description list elements (`<dl>`, `<dt>`, `<dd>`). These are largely based on the existing list styles.
<kbd><img width="1376" alt="image" src="https://github.com/tailwindlabs/tailwindcss-typography/assets/882133/80d7fa52-2025-4168-8d35-8452a5a8f12d"></kbd>
=> Add description list (`<dl>`, `<dt>`, `<dd>`) styles

src/styles.js
Based off #313, ensure the video selector order is maintained so that the figure margin 0 overrides it correctly, allowing captions to be closer to the video.
Before:
<kbd><img width="715" alt="image" src="https://github.com/tailwindlabs/tailwindcss-typography/assets/882133/168e9952-b5fa-4cd0-ac6e-749f0e187498"></kbd>
After:
<kbd><img width="721" alt="image" src="https://github.com/tailwindlabs/tailwindcss-typography/assets/882133/63bf6936-ce50-493b-8414-e8723eb3a96f"></kbd>
=> Fix space between `<figcaption>` and `<video>`

CHANGELOG.md, src/styles.js
Before this change the following would have unexpected extra space between the two lines of text in Firefox (but not in Safari or Chrome):
```html
<div className="prose">
<ul>
<li>
line 1
<br />
line 2
</li>
</ul>
</div>
```
Before, in FF:
After, in FF — now matching other browsers:
The intent of the selectors I've changed were to target leading/trailing `p` tags in a list item but we are targeting `*` instead. This had the side effect of causing `<br>` elements inside list items to gain a margin _only in Firefox_. Other browsers treat the `<br>` element like any other inline element and as such don’t apply margins.
Fixes #349
=> Don't apply margins to `<br>` elements contained in an `<li>` in FF

.github/workflows/nodejs.yml, .github/workflows/prepare-release.yml, .github/workflows/release-insiders.yml, .github/workflows/release.yml
This PR bumps the Node versions to 22 in the CI workflows.
For the general tests I also added an older version of Node 20.
Once this is merged, then #353 should work automatically.
=> Use Node 22 in CI workflows

src/styles.js
After this [commit](https://github.com/tailwindlabs/tailwindcss-typography/commit/f520c53470630e3ad4d43e3c2306882d33bf5c52), text alignment in tables no longer works as intended. It appears that `text-align: start;` does not apply correctly to the `table` tag.
To address this, I propose applying `text-align: start;` directly to the `th` and `td` tags, ensuring correct alignment.
=> Fix for the table `text-align: start`

CHANGELOG.md, package.json
Now that we have support for it, we should make `npm install @tailwindcss/forms` not fail 🙂 
The change was tested by installing it via a tarball.
=> Update peer dependency version to include 4.0.0-alpha.20

.github/workflows/nodejs.yml, .github/workflows/prepare-release.yml, .github/workflows/release-insiders.yml, .github/workflows/release.yml, CHANGELOG.md, README.md, demo/components/MarkdownSample.mdx, demo/components/MarkdownSampleShort.mdx
- Update branch references from `master` to `main`
- Modernize CI actions by updating to the latest version and relying on built-in cache mechanisms 
- Improve consistency in the change log by making sure every release has a proper heading
=> Modernize repository setup

src/utils.js
Map [returns a new array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), so we can just use that result directly, instead of spreading it into a new array!
=> Clean up extra spread array

CHANGELOG.md, package.json
Same as https://github.com/tailwindlabs/tailwindcss-typography/pull/358 but for beta releases.
=> Update peer dependency version to include 4.0.0-beta.1

README.md
=> Update README for Tailwind CSS v4

README.md
In the custom config JS part, the code example had a lot of trailing parentheses which leads to syntax errors if you simply copy/paste
=> Fix syntax errors in Readme.md

README.md
I think this is what it should be! The earlier version gave me an error with vite:
```
[plugin:@tailwindcss/vite:generate:serve] Package path ./typography is not exported from package  
.../.../node_modules/tailwindcss (see exports field in
```
Thank you for this wonderful project!
=> Fix plugin import path in README.md

CHANGELOG.md, src/styles.js
Noticed an invalid border width (`border-top-width`) value for the `hr` selector in DevTools. Despite that, the `hr` element is appearing as expected, inheriting the valid border width value from the preflight.
- Add a pixel string value for `borderTopWidth` property in the `hr` object in `styles.js`
=> Change the borderTopWidth value for hr from integer to a pixel value

README.md
The TW4 config does not need and use the `{theme}` anymore.
=> Readme: Remove unused `{theme}`

CHANGELOG.md, README.md, src/index.js, src/index.test.js
See https://github.com/tailwindlabs/tailwindcss-typography/issues/366
No idea if that is all that it takes, but if so, feel free to use this :)
=> Add `prose-picture` and `prose-images` modifiers

src/styles.js
Fixes bug where `hex` isn't defined due to [these recent changes](https://github.com/tailwindlabs/tailwindcss-typography/commit/f822222ae6e289e8cc0b23636891dc3545d5682a#diff-f3331a84c51a6f085fad8f853ae9dc1eb9188eca02f0ff692310780e4dfc58a0R10-R16)
=> Fix variable declaration in opacity function
